id: ABD6928FC
base_file: f8A04.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:06:35.249753
  last_modified_at: 2022-06-17 11:06:35.249759
