id: ABD6928FC
base_file: fF01B.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:06:35.265262
  last_modified_at: 2022-06-17 11:06:35.265265
