id: ABD6928FC
base_file: fAB48.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:06:35.259511
  last_modified_at: 2022-06-17 11:06:35.259514
