id: ABD6928FC
base_file: f99B2.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:06:35.251733
  last_modified_at: 2022-06-17 11:06:35.251738
