id: ABD6928FC
base_file: fA04E.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:06:35.254925
  last_modified_at: 2022-06-17 11:06:35.254929
