id: ABD6928FC
base_file: f83AC.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:06:35.247460
  last_modified_at: 2022-06-17 11:06:35.247465
