id: ABD6928FC
base_file: f145B.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:06:35.234731
  last_modified_at: 2022-06-17 11:06:35.234742
