id: ABD6928FC
base_file: fEB1A.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:06:35.263619
  last_modified_at: 2022-06-17 11:06:35.263622
