id: ABD6928FC
base_file: f9B37.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:06:35.253463
  last_modified_at: 2022-06-17 11:06:35.253467
