id: ABD6928FC
base_file: fC1E2.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:06:35.261057
  last_modified_at: 2022-06-17 11:06:35.261060
